# Generated by Django 5.2 on 2025-04-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('traffic_speed', models.FloatField(help_text='Speed in km/h')),
                ('traffic_density', models.IntegerField(blank=True, null=True)),
                ('traffic_condition', models.CharField(choices=[('traffic-heavy', 'Heavy'), ('traffic-moderate', 'Moderate'), ('traffic-free', 'Free-flowing')], max_length=50)),
                ('road_name', models.CharField(max_length=100)),
                ('road_type', models.CharField(choices=[('highway', 'Highway'), ('main_road', 'Main Road'), ('small_road', 'Small Road')], max_length=50)),
                ('distance_between_points', models.FloatField(help_text='Distance in meters')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('hour_of_day', models.TimeField()),
                ('month_collected', models.CharField(choices=[('October', 'October'), ('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March')], max_length=10)),
            ],
        ),
    ]
