# Generated by Django 5.2 on 2025-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='road_name',
            field=models.CharField(choices=[('Bahaddarhat', 'Bahaddarhat'), ('GEC Circle', 'GEC Circle'), ('New Market', 'New Market'), ('2 no Gate', '2 no Gate'), ('Oxygen Mor', 'Oxygen Mor'), ('Muradpur Mor', 'Muradpur Mor'), ('Agrabad Commercial Area', 'Agrabad Commercial Area'), ('EPZ', 'EPZ'), ('Chattogram Port', 'Chattogram Port'), ('Lalkhan Bazar', 'Lalkhan Bazar'), ('Wasa Mor', 'Wasa Mor')], max_length=100),
        ),
    ]
